[server]
headless = true
enableXsrfProtection = false
enableCORS = false
maxUploadSize = 10
port = 5000
address = "0.0.0.0"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[theme]
base = "light"
backgroundColor = "#F5F5F7"
secondaryBackgroundColor = "#FFFFFF"
primaryColor = "#0071E3"
textColor = "#1D1D1F"
font = "sans serif"
