[server]
headless = true
address = "0.0.0.0"
port = 5000
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
backgroundColor = "#060a11"
secondaryBackgroundColor = "#0a111e"
primaryColor = "#c0a062"
textColor = "#e8eaf0"
font = "sans serif"
